version: '2'
services:
    projeto1-elasticsearch:
        container_name: projeto1-elasticsearch
        image: elasticsearch:2.4.1
        # volumes:
        #     - ~/volumes/jhipster/projeto1/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
